# Generated by Django 3.1.5 on 2021-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210427_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
