# Generated by Django 3.1.5 on 2021-04-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='dat_of_death',
            new_name='date_of_death',
        ),
    ]
